# Generated by Django 2.2 on 2019-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20190417_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='profile_pics'),
        ),
    ]
