# Generated by Django 2.2 on 2019-04-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_auto_20190425_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
    ]
